# Generated by Django 3.0.2 on 2020-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id_category', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title_category', models.TextField()),
            ],
            options={
                'db_table': 'categorys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.SmallIntegerField()),
                ('title_category', models.TextField()),
            ],
            options={
                'db_table': 'cat_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'error_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id_podcast', models.IntegerField()),
                ('title_audio', models.TextField()),
                ('description_audio', models.TextField(blank=True, null=True)),
                ('audio', models.TextField()),
                ('image_audio', models.TextField(blank=True, null=True)),
                ('pubdata_audio', models.DateTimeField(blank=True, null=True)),
                ('duration_audio', models.CharField(blank=True, max_length=255, null=True)),
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsWithKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField()),
                ('id_keyword', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'items_with_keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id_keyword', models.AutoField(primary_key=True, serialize=False)),
                ('title_keyword', models.TextField()),
            ],
            options={
                'db_table': 'keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordsItems',
            fields=[
                ('id_keyword_item', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title_keyword', models.TextField()),
            ],
            options={
                'db_table': 'keywords_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('title_podcast', models.TextField()),
                ('description_podcast', models.TextField(blank=True, null=True)),
                ('url_image_podcast', models.TextField()),
                ('author_podcast', models.TextField(blank=True, null=True)),
                ('id_podcast', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'podcasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastsWithCategorys',
            fields=[
                ('id_podcast', models.IntegerField(primary_key=True, serialize=False)),
                ('id_category', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'podcasts_with_categorys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastsWithKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_podcast', models.IntegerField()),
                ('id_keyword', models.IntegerField()),
            ],
            options={
                'db_table': 'podcasts_with_keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcatItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.SmallIntegerField()),
                ('title_subcategory', models.TextField()),
            ],
            options={
                'db_table': 'subcat_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcatPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_podcast', models.IntegerField()),
                ('title_subcat', models.TextField()),
            ],
            options={
                'db_table': 'subcat_podcast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlPodcasts',
            fields=[
                ('url_podcast', models.TextField(verbose_name='Ссылка на подкаст')),
                ('status_podcast', models.IntegerField(default=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'url_podcasts',
                'managed': False,
            },
        ),
    ]
